</$objtype/mkfile

LIB=/$objtype/lib/libc.a

OFILES=\
	runenorm.$O\
	runetotype.$O\
	runeistype.$O\
	runebreak.$O\

CLEANFILES=$OFILES

HFILES=/sys/include/libc.h

</sys/src/cmd/mksyslib

DATA=\
	runenormdata\
	runetotypedata\
	runeistypedata\
	runebreakdata\

$OFILES: $DATA

UCD=\
	/lib/ucd/CompositionExclusions.txt\
	/lib/ucd/DerivedNormalizationProps.txt\
	/lib/ucd/GraphemeBreakProperty.txt\
	/lib/ucd/UnicodeData.txt\
	/lib/ucd/WordBreakProperty.txt\
	/lib/ucd/emoji-data.txt\

# build mkrunetype for the host regardless of $objtype,
# then use it to create the CPU-independent rune*data tables.
hostO=`{sed -n 's/^O=//p' /$cputype/mkfile}

$DATA:	$UCD
	$hostO^c $CFLAGS -o mkrunetype.$hostO mkrunetype.c
	$hostO^l -o $hostO.mkrunetype mkrunetype.$hostO
	./$hostO.mkrunetype

nuke:V:
	rm -f $DATA mkrunetype.[$OS] [$OS].mkrunetype
